app:
  build: .
  environment:
    RAILS_ENV: test
    DATABASE_URL: mysql2://root:root@mysql/railstest
  links:
  - "mysql:mysql"
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: railstest
